name: MOA_37
channels:
  - defaults
dependencies:
  - python=3.7
  - scikit-learn
  - numpy
  - jupyter
  - pandas
  - seaborn
  - matplotlib
  - sympy==1.5.1
  - networkx==2.4
  - cython
  - pip:
    - appdirs==1.4.4
    - category-encoders==2.2.2
    - chardet==3.0.4
    - fastcluster==1.1.26
    - idna==2.10
    - patsy==0.5.1
    - pyopencl==2019.1+cl12
    - python-slugify==4.0.1
    - pytools==2020.4.3
    - requests==2.24.0
    - slugify==0.0.1
    - statsmodels==0.12.0
    - text-unidecode==1.3
    - tqdm==4.49.0
    - urllib3==1.24.3
    - xgboost==1.2.0
    - xlrd==1.2.0
